version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: book_wise_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: book_wise
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
