export const books = [
  {
    id: "c8176d86-896a-4c21-9219-6bb28cccaa5f",
    name: "14 Hábitos de Desenvolvedores Altamente Produtivos",
    author: "Zeno Rocha",
    coverUrl:
      "/images/books/14-habitos-de-desenvolvedores-altamente-produtivos.png",
    totalPages: 160,
    categories: ["Educação", "Programação"],
  },
  {
    id: "375948a7-bca3-4b59-9f97-bfcde036b4ca",
    name: "O Hobbit",
    author: "J.R.R. Tolkien",
    coverUrl: "/images/books/o-hobbit.png",
    totalPages: 360,
    categories: ["Ficção", "Aventura"],
  },
  {
    id: "86596503-369b-4614-bacf-11c9bb73e779",
    name: "O guia do mochileiro das galáxias",
    author: "Douglas Adams",
    coverUrl: "/images/books/o-guia-do-mochileiro-das-galaxias.png",
    totalPages: 250,
    categories: ["Ficção", "Geek"],
  },
  {
    id: "d0d70b05-d48f-4d83-b1e8-0b4dd984c97d",
    name: "A revolução dos bichos",
    author: "George Orwell",
    coverUrl: "/images/books/a-revolucao-dos-bichos.png",
    totalPages: 350,
    categories: ["Alegoria", "Fábula"],
  },
  {
    id: "48b86ac2-014e-401d-bcbb-331ce5f4a457",
    name: "O fim da eternidade",
    author: "Isaac Asimov",
    coverUrl: "/images/books/o-fim-da-eternidade.png",
    totalPages: 165,
    categories: ["Ficção", "Romance"],
  },
  {
    id: "e688c24f-d14d-4607-a12e-90e6e367398d",
    name: "Entendendo Algoritmos",
    author: "Aditya Y. Bhargava",
    coverUrl: "/images/books/entendendo-algoritmos.png",
    totalPages: 165,
    categories: ["Programação", "Educação"],
  },
  {
    id: "0440ad7d-230e-4573-b455-84ca38b5d339",
    name: "Código Limpo",
    author: "Robert C. Martin",
    coverUrl: "/images/books/codigo-limpo.png",
    totalPages: 365,
    categories: ["Programação", "Educação"],
  },
  {
    id: "14f410df-b28a-4e72-b1b4-363e26e160dd",
    name: "O poder do hábito",
    author: "Charles Duhigg",
    coverUrl: "/images/books/o-poder-do-habito.png",
    totalPages: 288,
    categories: ["Autoajuda", "Educação"],
  },
  {
    id: "d2870ad0-3312-4ac2-af9f-76af6565587d",
    name: "Arquitetura limpa",
    author: "Robert C. Martin",
    coverUrl: "/images/books/arquitetura-limpa.png",
    totalPages: 288,
    categories: ["Programação", "Educação"],
  },
  {
    id: "4fd2b389-b211-40b5-9797-f78cbb985645",
    name: "Histórias extraordinárias",
    author: "Edgar Allan Poe",
    coverUrl: "/images/books/historias-extraordinarias.png",
    totalPages: 332,
    categories: ["Ficção", "Suspense"],
  },
  {
    id: "6de9f6b8-5ff4-4e06-b9f4-843eca462803",
    name: "Refatoração",
    author: "Martin Fowler",
    coverUrl: "/images/books/refatoracao.png",
    totalPages: 332,
    categories: ["Programação", "Educação"],
  },
  {
    id: "d0590f9a-dd89-42fd-9bbb-bf26c2e4dcf9",
    name: "Domain-Driven Design",
    author: "Eric Evans",
    coverUrl: "/images/books/domain-driven-design.png",
    totalPages: 288,
    categories: ["Programação", "Arquitetura"],
  },
  {
    id: "1d5cdbdc-b90f-40d5-8fe9-d4923ae12dbd",
    name: "Viagem ao Centro da Terra",
    author: "Julio Verne",
    coverUrl: "/images/books/viagem-ao-centro-da-terra.png",
    totalPages: 288,
    categories: ["Romance", "Ficção"],
  },
  {
    id: "404e47f8-da53-44fd-ab53-37ed171c3a9f",
    name: "Fragmentos do Horror",
    author: "Junji Ito",
    coverUrl: "/images/books/fragmentos-do-horror.png",
    totalPages: 144,
    categories: ["Ficção", "Terror"],
  },
  {
    id: "66cb0f47-7e20-4492-b640-9c020fcae6f2",
    name: "O Programador Pragmático",
    author: "Andrew Hunt",
    coverUrl: "/images/books/o-programador-pragmatico.png",
    totalPages: 205,
    categories: ["Programação", "Educação"],
  },
];
